### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by natanarie** [ArtSabintsev/Ethminer-for-macOS#10]
All steps i have done so far.

`git clone --recursive https://github.com/ArtSabintsev/Ethminer-for-macOS`
`mkdir build; cd build`
`cmake /Users/paolo/Ethminer-for-macOS/ethminer -DBUNDLE=cudaminer -DETHSTRATUM=1` .. //all without issues so far
`make -j8`

> Scanning dependencies of target ethminer
[ 50%] Building CXX object CMakeFiles/ethminer.dir/main.o
In file included from /Users/paolo/Ethminer-for-macOS/ethminer/main.cpp:38:
In file included from /Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/FileSystem.h:27:
In file included from /Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/CommonIO.h:39:
In file included from /Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:56:
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/vector_ref.h:19:21: warning: 
      alias declarations are a C++11 extension [-Wc++11-extensions]
        using value_type = _T;
                           ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/vector_ref.h:20:23: warning: 
      alias declarations are a C++11 extension [-Wc++11-extensions]
        using element_type = _T;
                             ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/vector_ref.h:21:29: warning: 
      alias declarations are a C++11 extension [-Wc++11-extensions]
        using mutable_value_type = typename std::conditional<std::is_con...
                                   ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/vector_ref.h:37:2: warning: 
      explicit conversion functions are a C++11 extension [-Wc++11-extensions]
        explicit operator bool() const { return m_data && m_count; }
        ^~~~~~~~
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/vector_ref.h:44:23: warning: 
      explicit conversion functions are a C++11 extension [-Wc++11-extensions]
        template <class _T2> explicit operator vector_ref<_T2>() const ...
                             ^~~~~~~~
In file included from /Users/paolo/Ethminer-for-macOS/ethminer/main.cpp:38:
In file included from /Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/FileSystem.h:27:
In file included from /Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/CommonIO.h:39:
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:59:14: warning: 
      alias declarations are a C++11 extension [-Wc++11-extensions]
using byte = uint8_t;
             ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:78:15: warning: 
      alias declarations are a C++11 extension [-Wc++11-extensions]
using bytes = std::vector<byte>;
              ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:79:18: warning: 
      alias declarations are a C++11 extension [-Wc++11-extensions]
using bytesRef = vector_ref<byte>;
                 ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:80:23: warning: 
      alias declarations are a C++11 extension [-Wc++11-extensions]
using bytesConstRef = vector_ref<byte const>;
                      ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:87:46: warning: 
      defaulted function definitions are a C++11 extension [-Wc++11-extensions]
        secure_vector(secure_vector<T> const& _c) = default;
                                                    ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:121:18: warning: 
      alias declarations are a C++11 extension [-Wc++11-extensions]
using bytesSec = secure_vector<byte>;
                 ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:124:16: warning: 
      alias declarations are a C++11 extension [-Wc++11-extensions]
using bigint = boost::multiprecision::number<boost::multiprecision::cpp_...
               ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:124:85: error: 
      a space is required between consecutive right angle brackets (use '> >')
  ...boost::multiprecision::number<boost::multiprecision::cpp_int_backend<>>;
                                                                          ^~
                                                                          > >
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:125:14: warning: 
      alias declarations are a C++11 extension [-Wc++11-extensions]
using u64 =  boost::multiprecision::number<boost::multiprecision::cpp_in...
             ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:125:172: error: 
      a space is required between consecutive right angle brackets (use '> >')
  ...boost::multiprecision::unchecked, void>>;
                                           ^~
                                           > >
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:126:15: warning: 
      alias declarations are a C++11 extension [-Wc++11-extensions]
using u128 =  boost::multiprecision::number<boost::multiprecision::cpp_i...
              ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:126:175: error: 
      a space is required between consecutive right angle brackets (use '> >')
  ...boost::multiprecision::unchecked, void>>;
                                           ^~
                                           > >
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:127:15: warning: 
      alias declarations are a C++11 extension [-Wc++11-extensions]
using u256 =  boost::multiprecision::number<boost::multiprecision::cpp_i...
              ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:127:175: error: 
      a space is required between consecutive right angle brackets (use '> >')
  ...boost::multiprecision::unchecked, void>>;
                                           ^~
                                           > >
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:128:15: warning: 
      alias declarations are a C++11 extension [-Wc++11-extensions]
using s256 =  boost::multiprecision::number<boost::multiprecision::cpp_i...
              ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:128:173: error: 
      a space is required between consecutive right angle brackets (use '> >')
  ...boost::multiprecision::unchecked, void>>;
                                           ^~
                                           > >
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:129:15: warning: 
      alias declarations are a C++11 extension [-Wc++11-extensions]
using u160 =  boost::multiprecision::number<boost::multiprecision::cpp_i...
              ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:129:175: error: 
      a space is required between consecutive right angle brackets (use '> >')
  ...boost::multiprecision::unchecked, void>>;
                                           ^~
                                           > >
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:130:15: warning: 
      alias declarations are a C++11 extension [-Wc++11-extensions]
using s160 =  boost::multiprecision::number<boost::multiprecision::cpp_i...
              ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:130:173: error: 
      a space is required between consecutive right angle brackets (use '> >')
  ...boost::multiprecision::unchecked, void>>;
                                           ^~
                                           > >
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:131:15: warning: 
      alias declarations are a C++11 extension [-Wc++11-extensions]
using u512 =  boost::multiprecision::number<boost::multiprecision::cpp_i...
              ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:131:175: error: 
      a space is required between consecutive right angle brackets (use '> >')
  ...boost::multiprecision::unchecked, void>>;
                                           ^~
                                           > >
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:132:15: warning: 
      alias declarations are a C++11 extension [-Wc++11-extensions]
using u256s = std::vector<u256>;
              ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:133:15: warning: 
      alias declarations are a C++11 extension [-Wc++11-extensions]
using u160s = std::vector<u160>;
              ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:134:17: warning: 
      alias declarations are a C++11 extension [-Wc++11-extensions]
using u256Set = std::set<u256>;
                ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:135:17: warning: 
      alias declarations are a C++11 extension [-Wc++11-extensions]
using u160Set = std::set<u160>;
                ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:140:19: warning: 
      alias declarations are a C++11 extension [-Wc++11-extensions]
using StringMap = std::map<std::string, std::string>;
                  ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:141:18: warning: 
      alias declarations are a C++11 extension [-Wc++11-extensions]
using BytesMap = std::map<bytes, bytes>;
                 ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:142:17: warning: 
      alias declarations are a C++11 extension [-Wc++11-extensions]
using u256Map = std::map<u256, u256>;
                ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:143:16: warning: 
      alias declarations are a C++11 extension [-Wc++11-extensions]
using HexMap = std::map<bytes, bytes>;
               ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:146:23: warning: 
      alias declarations are a C++11 extension [-Wc++11-extensions]
using StringHashMap = std::unordered_map<std::string, std::string>;
                      ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:147:21: warning: 
      alias declarations are a C++11 extension [-Wc++11-extensions]
using u256HashMap = std::unordered_map<u256, u256>;
                    ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:150:17: warning: 
      alias declarations are a C++11 extension [-Wc++11-extensions]
using strings = std::vector<std::string>;
                ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:153:18: warning: 
      alias declarations are a C++11 extension [-Wc++11-extensions]
using string32 = std::array<char, 32>;
                 ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:289:6: warning: 
      scoped enumerations are a C++11 extension [-Wc++11-extensions]
enum class WithExisting: int
     ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:289:12: error: 
      ISO C++ forbids forward references to 'enum' types
enum class WithExisting: int
           ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:289:24: error: 
      expected unqualified-id
enum class WithExisting: int
                       ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Common.h:312:3: warning: 
      'auto' type specifier is a C++11 extension [-Wc++11-extensions]
                auto limbs = _a.backend().limbs();
                ^
In file included from /Users/paolo/Ethminer-for-macOS/ethminer/main.cpp:38:
In file included from /Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/FileSystem.h:27:
In file included from /Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/CommonIO.h:40:
In file included from /Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Base64.h:33:
In file included from /Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/FixedHash.h:31:
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/CommonData.h:39:6: warning: 
      scoped enumerations are a C++11 extension [-Wc++11-extensions]
enum class WhenError
     ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/CommonData.h:45:6: warning: 
      scoped enumerations are a C++11 extension [-Wc++11-extensions]
enum class HexPrefix
     ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/CommonData.h:54:67: warning: 
      use of enumeration in a nested name specifier is a C++11 extension
      [-Wc++11-extensions]
  ...toHex(T const& _data, int _w = 2, HexPrefix _prefix = HexPrefix::DontAdd)
                                                           ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/CommonData.h:58:7: warning: 
      'auto' type specifier is a C++11 extension [-Wc++11-extensions]
        for (auto i: _data)
             ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/CommonData.h:58:13: warning: 
      range-based for loop is a C++11 extension [-Wc++11-extensions]
        for (auto i: _data)
                   ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/CommonData.h:60:21: warning: 
      use of enumeration in a nested name specifier is a C++11 extension
      [-Wc++11-extensions]
        return (_prefix == HexPrefix::Add) ? "0x" + ret.str() : ret.str();
                           ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/CommonData.h:70:57: warning: 
      use of enumeration in a nested name specifier is a C++11 extension
      [-Wc++11-extensions]
bytes fromHex(std::string const& _s, WhenError _throw = WhenError::DontThrow);
                                                        ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/CommonData.h:107:86: error: 
      too many arguments provided to function-like macro invocation
  ...T>::value || !std::numeric_limits<T>::is_signed, "only unsigned types o...
                                                      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__config:600:9: note: 
      macro 'static_assert' defined here
#define static_assert(__b, __m) \
        ^
In file included from /Users/paolo/Ethminer-for-macOS/ethminer/main.cpp:38:
In file included from /Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/FileSystem.h:27:
In file included from /Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/CommonIO.h:40:
In file included from /Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Base64.h:33:
In file included from /Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/FixedHash.h:31:
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/CommonData.h:107:2: error: 
      use of undeclared identifier 'static_assert'
        static_assert(std::is_same<bigint, T>::value || !std::numeric_li...
        ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/CommonData.h:108:7: warning: 
      'auto' type specifier is a C++11 extension [-Wc++11-extensions]
        for (auto i = o_out.size(); i != 0; _val >>= 8, i--)
             ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/CommonData.h:122:7: warning: 
      'auto' type specifier is a C++11 extension [-Wc++11-extensions]
        for (auto i: _bytes)
             ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/CommonData.h:122:13: warning: 
      range-based for loop is a C++11 extension [-Wc++11-extensions]
        for (auto i: _bytes)
                   ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/CommonData.h:138:86: error: 
      too many arguments provided to function-like macro invocation
  ...T>::value || !std::numeric_limits<T>::is_signed, "only unsigned types o...
                                                      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__config:600:9: note: 
      macro 'static_assert' defined here
#define static_assert(__b, __m) \
        ^
In file included from /Users/paolo/Ethminer-for-macOS/ethminer/main.cpp:38:
In file included from /Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/FileSystem.h:27:
In file included from /Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/CommonIO.h:40:
In file included from /Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Base64.h:33:
In file included from /Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/FixedHash.h:31:
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/CommonData.h:138:2: error: 
      use of undeclared identifier 'static_assert'
        static_assert(std::is_same<bigint, T>::value || !std::numeric_li...
        ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/CommonData.h:147:31: error: 
      expected '(' for function-style cast or type construction
        return (_min || _val) ? bytes{ _val } : bytes{};
                                ~~~~~^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/CommonData.h:147:31: error: 
      expected ':'
        return (_min || _val) ? bytes{ _val } : bytes{};
                                     ^
                                     : 
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/CommonData.h:147:24: note: 
      to match this '?'
        return (_min || _val) ? bytes{ _val } : bytes{};
                              ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/CommonData.h:147:31: error: 
      expected expression
        return (_min || _val) ? bytes{ _val } : bytes{};
                                     ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/CommonData.h:155:86: error: 
      too many arguments provided to function-like macro invocation
  ...T>::value || !std::numeric_limits<T>::is_signed, "only unsigned types o...
                                                      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__config:600:9: note: 
      macro 'static_assert' defined here
#define static_assert(__b, __m) \
        ^
In file included from /Users/paolo/Ethminer-for-macOS/ethminer/main.cpp:38:
In file included from /Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/FileSystem.h:27:
In file included from /Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/CommonIO.h:40:
In file included from /Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/Base64.h:33:
In file included from /Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/FixedHash.h:31:
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/CommonData.h:155:2: error: 
      use of undeclared identifier 'static_assert'
        static_assert(std::is_same<bigint, T>::value || !std::numeric_li...
        ^
/Users/paolo/Ethminer-for-macOS/ethminer/../libdevcore/CommonData.h:164:55: warning: 
      use of enumeration in a nested name specifier is a C++11 extension
      [-Wc++11-extensions]
inline std::string toHex(u256 val, HexPrefix prefix = HexPrefix::DontAdd)
                                                      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
44 warnings and 20 errors generated.
make[2]: *** [CMakeFiles/ethminer.dir/main.o] Error 1
make[1]: *** [CMakeFiles/ethminer.dir/all] Error 2
make: *** [all] Error 2

**Comment by ArtSabintsev** [comment]
Did you make and enter the `build` directory within the downloaded directory?

**Comment by natanarie** [comment]
Yes I did. I did not mention however that the cmake command did give me the following:

> -- The C compiler identification is AppleClang 8.1.0.8020042
-- The CXX compiler identification is AppleClang 8.1.0.8020042
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

   

> cmake_minimum_required(VERSION 3.8)

 

> should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

> --Configuring done
CMake Warning (dev) at CMakeLists.txt:24 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

 

> The dependency target "BuildInfo.h" of target "ethminer" does not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

> -- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

 

>   BUNDLE


> --Build files have been written to: /Users/paolo/Ethminer-for-macOS/build

**Comment by ArtSabintsev** [comment]
Have you tried installing with `cmake -DBUNDLE=miner` - trying to eliminate a specific issue before proceeding forward.

**Comment by natanarie** [comment]
tried also with` cmake -DBUNDLE=miner` but I get the same result

**Comment by ArtSabintsev** [comment]
Honestly, no idea.

Shooting in the dark here, but do you have the correct version of Xcode installed?

I don't think I'll be of much help. I fixed this project up for myself, but since then, haven't opened or touched it, or cared to really even try to fix the dangling warnings and any existing issues,

**Comment by natanarie** [comment]
My version of Xcode is 8.3.3

**Comment by ArtSabintsev** [comment]
Per the `Pre-Installation Instructions`, you need Xcode 8.2 for nvidia cards: https://github.com/ArtSabintsev/Ethminer-for-macOS#pre-installation-instructions

**Comment by ArtSabintsev** [comment]
Closing due to lack of follow-up.
