### ISSUE TITLE
Json::LogicError: Value is not convertible to bool.

### ISSUE THREAD

**Issue by keithyau** [ArtSabintsev/Ethminer-for-macOS#11]
Im using yosemite Mac Pro D300

and having following error, libc++abi.dylib: terminating with uncaught exception of type Json::LogicError: Value is not convertible to bool.

Please provide the following information in your issue:
- Entire stacktrace, including your commands.
./ethminer -G -S eth-eu.dwarfpool.com:8008 -O xxxxxxxxxxx.macpro --opencl-device 0 1

Ethminer for macOS (Fixed by ArtSabintsev)
=====================================================================
Forked from github.com/genoil/cpp-ethereum, which itself was forked from github.com/ethereum/cpp-ethereum.
CUDA kernel ported from Tim Hughes' OpenCL kernel
With contributions from nicehash, nerdralph, RoBiK and sp_

Please consider a donation to:
ArtSabintsev's ETH: 0x1e8cce03A2C01d18C5a68F410bfE34eea1aa16f2
Genoil's ETH: 0xeb9310b185455f863f526dab3d245809f6854b4d

[OPENCL]:Found suitable OpenCL device [AMD Radeon HD - FirePro D300 Compute Engine] with 2147483648 bytes of GPU memory
  ℹ  20:56:23|  Connecting to stratum server eth-eu.dwarfpool.com:8008
  ℹ  20:56:24|stratum  Connected to stratum server eth-eu.dwarfpool.com : 8008
  ℹ  20:56:24|stratum  Starting farm
  ℹ  20:56:24|stratum  Subscribed to stratum server
libc++abi.dylib: terminating with uncaught exception of type Json::LogicError: Value is not convertible to bool.
Abort trap: 6

- Are you using OpenCL or CUDA?
OpenCL
  - There are issues with CUDA that have yet to be resolved. 

Please kindly help, i also tried the official ethminer which had the same issue.

**Comment by keithyau** [comment]
-SP to change protocol

**Comment by ArtSabintsev** [comment]
Guess you fixed this issue.
