### ISSUE TITLE
GPU can't allocate the DAG in a single chunk

### ISSUE THREAD

**Issue by rosswlewis** [ArtSabintsev/Ethminer-for-macOS#12]
Is there any way around the 
```
Allocating/mapping DAG buffer failed with: clCreateBuffer(-61). GPU can't allocate the DAG in a single chunk. Bailing.
```
error for macs that have a 2gb gpu?  [Updating environmental variables](http://cryptomining-blog.com/7606-how-to-fix-ethminer-not-working-issues-on-2gb-gpus/) doesn't seem to help.

- Are you using OpenCL or CUDA?  OpenCL

**Comment by ArtSabintsev** [comment]
If I recall correctly, this means you don't have enough memory on your machine to parse a DAG.

**Comment by rosswlewis** [comment]
That's correct.  I'm working with a 2GB gpu:
```
[1] AMD Radeon R9 M370X Compute Engine
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 2147483648
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 536870912
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
```
I was hoping I could still get some use out of it but am I attempting an impossible task with this hardware?

**Comment by ArtSabintsev** [comment]
yup, you are.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jongwook** [comment]
I was able to launch it after switching the screen into ultra low resolution (used SwitchResX) and rebooting.
