### ISSUE TITLE
Not able to use GPU

### ISSUE THREAD

**Issue by quixoticblink** [ArtSabintsev/Ethminer-for-macOS#13]
[OPENCL]:Found suitable OpenCL device [Intel(R) HD Graphics 530] with 1610612736 bytes of GPU memory
  m  00:38:54|  Getting work package...
  ✘  00:38:54|  Failed to submit hashrate.
  ✘  00:38:54|  Dynamic exception type: jsonrpc::JsonRpcException
std::exception::what: Exception -32003 : Client connector error: libcurl error: 7 -> Could not connect to http://127.0.0.1:8545
JSON-RPC problem. Probably couldn't connect. Retrying in 1... 
  m  00:38:56|  Getting work package...
  ✘  00:38:56|  Failed to submit hashrate.
  ✘  00:38:56|  Dynamic exception type: jsonrpc::JsonRpcException
std::exception::what: Exception -32003 : Client connector error: libcurl error: 7 -> Could not connect to http://127.0.0.1:8545

**Comment by quixoticblink** [comment]
Thank you for the detailed instructions...solved the above issue
Now I see although the system has received the jobs and there is no update since hours.
Can you please advice 


$ ./ethminer -G -S asia1.ethpool.org:3333 -O 0x5f3392258f19ae89736c91ef65fc9D8b5B22BF05 --opencl-devices 
Ethminer for macOS (Fixed by ArtSabintsev)
=====================================================================
Forked from github.com/genoil/cpp-ethereum, which itself was forked from github.com/ethereum/cpp-ethereum.
CUDA kernel ported from Tim Hughes' OpenCL kernel
With contributions from nicehash, nerdralph, RoBiK and sp_

Please consider a donation to:
ArtSabintsev's ETH: 0x1e8cce03A2C01d18C5a68F410bfE34eea1aa16f2
Genoil's ETH: 0xeb9310b185455f863f526dab3d245809f6854b4d

[OPENCL]:Found suitable OpenCL device [Intel(R) HD Graphics 530] with 1610612736 bytes of GPU memory
  ℹ  02:08:44|  Connecting to stratum server asia1.ethpool.org:3333
  ℹ  02:08:45|stratum  Connected to stratum server asia1.ethpool.org : 3333
  ℹ  02:08:45|stratum  Starting farm
  ℹ  02:08:45|stratum  Subscribed to stratum server
  ℹ  02:08:45|stratum  Authorized worker 0x5f3392258f19ae89736c91ef65fc9D8b5B22BF05
  ℹ  02:08:45|stratum  Received new job #b2f536c3
  ℹ  02:08:45|openclminer0  set work; seed: #19b5edd8, target:  #0000000112e0
  ℹ  02:08:45|openclminer1  set work; seed: #19b5edd8, target:  #0000000112e0
  ℹ  02:08:45|openclminer0  Initialising miner...
  ℹ  02:08:45|openclminer1  Initialising miner...
  m  02:08:46|  Mining on PoWhash #b2f536c3 : 0.00MH/s [A0+0:R0+0:F0]
[OPENCL]:Using platform: Apple
[OPENCL]:Using platform: Apple
[OPENCL]:Using device: [OPENCL]:Intel(R) HD Graphics 530Using device: (AMD Radeon Pro 450 Compute EngineOpenCL 1.2 ()OpenCL 1.2 
)
[OPENCL]:Printing program log
[OPENCL]:
[OPENCL]:Creating cache buffer
[OPENCL]:Creating DAG buffer
[OPENCL]:Allocating/mapping DAG buffer failed with: clCreateBuffer(-61). GPU can't allocate the DAG in a single chunk. Bailing.
[OPENCL]:clEnqueueWriteBuffer(-38)
[OPENCL]:Printing program log
[OPENCL]:
[OPENCL]:Creating cache buffer
[OPENCL]:Creating DAG buffer
[OPENCL]:Allocating/mapping DAG buffer failed with: clCreateBuffer(-61). GPU can't allocate the DAG in a single chunk. Bailing.
[OPENCL]:clEnqueueWriteBuffer(-38)
  m  02:08:48|  Mining on PoWhash #b2f536c3 : 0.00MH/s [A0+0:R0+0:F0]
  m  02:08:50|  Mining on PoWhash #b2f536c3 : 0.00MH/s [A0+0:R0+0:F0]
  m  02:08:52|  Mining on PoWhash #b2f536c3 : 0.00MH/s [A0+0:R0+0:F0]
  m  02:08:54|  Mining on PoWhash #b2f536c3 : 0.00MH/s [A0+0:R0+0:F0]
  m  02:08:56|  Mining on PoWhash #b2f536c3 : 0.00MH/s [A0+0:R0+0:F0]
  m  02:08:58|  Mining on PoWhash #b2f536c3 : 0.00MH/s [A0+0:R0+0:F0]
  ℹ  02:09:00|stratum  Received new job #6a455400

**Comment by ArtSabintsev** [comment]
`GPU can't allocate the DAG in a single chunk. Bailing.` 

This error means you don't have enough memory to parse a DAG file, which means you cannot mine Ethereum on your machine.
