### ISSUE TITLE
Nvidia GTX eGPU

### ISSUE THREAD

**Issue by SnyderMark** [ArtSabintsev/Ethminer-for-macOS#14]
Hello Art,
I am running a Bizon Box with an eGPU. It's a Nvidia GTX 970 (Cuda enabled card)
How to compile Ethminer with CUDA? When adding -U to the string I get this:
Selected CUDA mining without having compiled with -DETHASHCUDA=1 or -DBUNDLE=cudaminer-.
How do I compile with -DETHASHCUDA=1 or -DBUNDLE=cudaminer?
When adding  -G and --opencl-device 1, the DAG gets written and appears to be mining, but isn't.
I've attached the output. The GTX is recognized, yet not. Is it possible to mine with only the external card? 

Thanks!
Mark 

MacBook-Pro:ethminer marksnyder$ ./ethminer -G -F http://eth.pool.minergate.com:55751/flatbreadco@live.ca --opencl-device 1
Ethminer for macOS (Fixed by ArtSabintsev)
=====================================================================
Forked from github.com/genoil/cpp-ethereum, which itself was forked from github.com/ethereum/cpp-ethereum.
CUDA kernel ported from Tim Hughes' OpenCL kernel
With contributions from nicehash, nerdralph, RoBiK and sp_

Please consider a donation to:
ArtSabintsev's ETH: 0x1e8cce03A2C01d18C5a68F410bfE34eea1aa16f2
Genoil's ETH: 0xeb9310b185455f863f526dab3d245809f6854b4d

[OPENCL]:Found suitable OpenCL device [HD Graphics 4000] with 1610612736 bytes of GPU memory
  m  08:43:18|  Getting work package...
  m  08:43:19|  Got work package: #88141cff
  ℹ  08:43:19|openclminer0  set work; seed: #e0d55f3f, target:  #000000044b82
  ℹ  08:43:19|openclminer0  Initialising miner...
  m  08:43:19|  Mining on PoWhash #88141cff : 0.00MH/s [A0+0:R0+0:F0]
  m  08:43:20|  Mining on PoWhash #88141cff : 0.00MH/s [A0+0:R0+0:F0]
[OPENCL]:Using platform: Apple
[OPENCL]:Using device: GeForce GTX 970(OpenCL 1.2 )
[OPENCL]:Printing program log
[OPENCL]:
[OPENCL]:Creating cache buffer
[OPENCL]:Creating DAG buffer
[OPENCL]:Loading kernels
[OPENCL]:Writing cache buffer
[OPENCL]:Creating buffer for header.
[OPENCL]:Creating mining buffer 0
[OPENCL]:Creating mining buffer 1
[OPENCL]:Generating DAG data
OPENCL#1: 0%
OPENCL#1: 1%
OPENCL#1: 1%
OPENCL#1: 2%
OPENCL#1: 3%
OPENCL#1: 4%
OPENCL#1: 4%
OPENCL#1: 5%
OPENCL#1: 6%
OPENCL#1: 7%
OPENCL#1: 7%
OPENCL#1: 8%
OPENCL#1: 9%
OPENCL#1: 9%
OPENCL#1: 10%
OPENCL#1: 11%
OPENCL#1: 12%
OPENCL#1: 12%
OPENCL#1: 13%
OPENCL#1: 14%
OPENCL#1: 15%
OPENCL#1: 15%
OPENCL#1: 16%
OPENCL#1: 17%
OPENCL#1: 18%
OPENCL#1: 18%
OPENCL#1: 19%
OPENCL#1: 20%
OPENCL#1: 20%
OPENCL#1: 21%
OPENCL#1: 22%
OPENCL#1: 23%
OPENCL#1: 23%
OPENCL#1: 24%
OPENCL#1: 25%
OPENCL#1: 26%
OPENCL#1: 26%
OPENCL#1: 27%
OPENCL#1: 28%
OPENCL#1: 28%
OPENCL#1: 29%
OPENCL#1: 30%
OPENCL#1: 31%
OPENCL#1: 31%
OPENCL#1: 32%
OPENCL#1: 33%
OPENCL#1: 34%
OPENCL#1: 34%
OPENCL#1: 35%
OPENCL#1: 36%
OPENCL#1: 36%
OPENCL#1: 37%
OPENCL#1: 38%
OPENCL#1: 39%
OPENCL#1: 39%
OPENCL#1: 40%
OPENCL#1: 41%
OPENCL#1: 42%
OPENCL#1: 42%
OPENCL#1: 43%
OPENCL#1: 44%
OPENCL#1: 45%
OPENCL#1: 45%
OPENCL#1: 46%
OPENCL#1: 47%
OPENCL#1: 47%
OPENCL#1: 48%
OPENCL#1: 49%
OPENCL#1: 50%
OPENCL#1: 50%
OPENCL#1: 51%
OPENCL#1: 52%
OPENCL#1: 53%
OPENCL#1: 53%
OPENCL#1: 54%
OPENCL#1: 55%
OPENCL#1: 55%
OPENCL#1: 56%
OPENCL#1: 57%
OPENCL#1: 58%
OPENCL#1: 58%
OPENCL#1: 59%
OPENCL#1: 60%
OPENCL#1: 61%
OPENCL#1: 61%
OPENCL#1: 62%
OPENCL#1: 63%
OPENCL#1: 64%
OPENCL#1: 64%
OPENCL#1: 65%
OPENCL#1: 66%
OPENCL#1: 66%
OPENCL#1: 67%
OPENCL#1: 68%
OPENCL#1: 69%
OPENCL#1: 69%
OPENCL#1: 70%
OPENCL#1: 71%
OPENCL#1: 72%
OPENCL#1: 72%
OPENCL#1: 73%
OPENCL#1: 74%
OPENCL#1: 74%
OPENCL#1: 75%
OPENCL#1: 76%
OPENCL#1: 77%
OPENCL#1: 77%
OPENCL#1: 78%
OPENCL#1: 79%
OPENCL#1: 80%
OPENCL#1: 80%
OPENCL#1: 81%
OPENCL#1: 82%
OPENCL#1: 82%
OPENCL#1: 83%
OPENCL#1: 84%
OPENCL#1: 85%
OPENCL#1: 85%
OPENCL#1: 86%
OPENCL#1: 87%
OPENCL#1: 88%
OPENCL#1: 88%
OPENCL#1: 89%
OPENCL#1: 90%
OPENCL#1: 91%
OPENCL#1: 91%
OPENCL#1: 92%
OPENCL#1: 93%
OPENCL#1: 93%
OPENCL#1: 94%
OPENCL#1: 95%
OPENCL#1: 96%
OPENCL#1: 96%
OPENCL#1: 97%
OPENCL#1: 98%
OPENCL#1: 99%
OPENCL#1: 99%
  m  08:43:20|  Mining on PoWhash #88141cff : 691.24MH/s [A0+0:R0+0:F0]
  m  08:43:21|  Mining on PoWhash #88141cff : 1875.39MH/s [A0+0:R0+0:F0]
  m  08:43:22|  Mining on PoWhash #88141cff : 1878.27MH/s [A0+0:R0+0:F0]
  m  08:43:23|  Mining on PoWhash #88141cff : 1874.69MH/s [A0+0:R0+0:F0]
  m  08:43:23|  Mining on PoWhash #88141cff : 1873.76MH/s [A0+0:R0+0:F0]
  m  08:43:24|  Mining on PoWhash #88141cff : 1873.08MH/s [A0+0:R0+0:F0]
  m  08:43:25|  Mining on PoWhash #88141cff : 1878.15MH/s [A0+0:R0+0:F0]
  m  08:43:26|  Mining on PoWhash #88141cff : 1879.31MH/s [A0+0:R0+0:F0]
  m  08:43:26|  Mining on PoWhash #88141cff : 1832.46MH/s [A0+0:R0+0:F0]
  m  08:43:27|  Mining on PoWhash #88141cff : 1899.72MH/s [A0+0:R0+0:F0]
  m  08:43:28|  Mining on PoWhash #88141cff : 1897.54MH/s [A0+0:R0+0:F0]
  m  08:43:28|  Mining on PoWhash #88141cff : 1892.42MH/s [A0+0:R0+0:F0]
  m  08:43:29|  Mining on PoWhash #88141cff : 1897.35MH/s [A0+0:R0+0:F0]
  m  08:43:30|  Mining on PoWhash #88141cff : 1887.80MH/s [A0+0:R0+0:F0]
  m  08:43:31|  Mining on PoWhash #88141cff : 1868.74MH/s [A0+0:R0+0:F0]
  m  08:43:31|  Mining on PoWhash #88141cff : 1856.52MH/s [A0+0:R0+0:F0]
  m  08:43:32|  Mining on PoWhash #88141cff : 1880.34MH/s [A0+0:R0+0:F0]
  m  08:43:33|  Mining on PoWhash #88141cff : 1872.25MH/s [A0+0:R0+0:F0]
  m  08:43:33|  Mining on PoWhash #88141cff : 1868.37MH/s [A0+0:R0+0:F0]
  m  08:43:34|  Mining on PoWhash #88141cff : 1873.19MH/s [A0+0:R0+0:F0]
  m  08:43:35|  Mining on PoWhash #88141cff : 1683.59MH/s [A0+0:R0+0:F0]
  m  08:43:36|  Mining on PoWhash #88141cff : 1784.41MH/s [A0+0:R0+0:F0]
  m  08:43:36|  Mining on PoWhash #88141cff : 1808.65MH/s [A0+0:R0+0:F0]
  m  08:43:37|  Mining on PoWhash #88141cff : 1847.06MH/s [A0+0:R0+0:F0]
  m  08:43:38|  Mining on PoWhash #88141cff : 1943.01MH/s [A0+0:R0+0:F0]
  m  08:43:38|  Mining on PoWhash #88141cff : 1922.76MH/s [A0+0:R0+0:F0]
  m  08:43:39|  Mining on PoWhash #88141cff : 1980.93MH/s [A0+0:R0+0:F0]
  m  08:43:40|  Mining on PoWhash #88141cff : 1979.46MH/s [A0+0:R0+0:F0]
  m  08:43:41|  Mining on PoWhash #88141cff : 1957.44MH/s [A0+0:R0+0:F0]
  m  08:43:41|  Mining on PoWhash #88141cff : 1937.16MH/s [A0+0:R0+0:F0]
  m  08:43:42|  Mining on PoWhash #88141cff : 1953.01MH/s [A0+0:R0+0:F0]
  m  08:43:43|  Mining on PoWhash #88141cff : 1980.60MH/s [A0+0:R0+0:F0]
  m  08:43:43|  Mining on PoWhash #88141cff : 1955.83MH/s [A0+0:R0+0:F0]
  m  08:43:44|  Mining on PoWhash #88141cff : 1976.16MH/s [A0+0:R0+0:F0]
  m  08:43:45|  Mining on PoWhash #88141cff : 1978.99MH/s [A0+0:R0+0:F0]
  m  08:43:46|  Mining on PoWhash #88141cff : 1971.21MH/s [A0+0:R0+0:F0]
  m  08:43:46|  Mining on PoWhash #88141cff : 1966.81MH/s [A0+0:R0+0:F0]
  m  08:43:47|  Mining on PoWhash #88141cff : 1931.20MH/s [A0+0:R0+0:F0]
  m  08:43:48|  Mining on PoWhash #88141cff : 1925.30MH/s [A0+0:R0+0:F0]
  m  08:43:48|  Mining on PoWhash #88141cff : 1942.00MH/s [A0+0:R0+0:F0]
  m  08:43:49|  Mining on PoWhash #88141cff : 1829.89MH/s [A0+0:R0+0:F0]
  m  08:43:50|  Mining on PoWhash #88141cff : 1796.10MH/s [A0+0:R0+0:F0]
  m  08:43:51|  Mining on PoWhash #88141cff : 1775.70MH/s [A0+0:R0+0:F0]
  m  08:43:51|  Mining on PoWhash #88141cff : 1797.14MH/s [A0+0:R0+0:F0]
  m  08:43:52|  Mining on PoWhash #88141cff : 1950.34MH/s [A0+0:R0+0:F0]
  m  08:43:53|  Mining on PoWhash #88141cff : 1959.32MH/s [A0+0:R0+0:F0]
  m  08:43:54|  Mining on PoWhash #88141cff : 1969.71MH/s [A0+0:R0+0:F0]
  m  08:43:54|  Mining on PoWhash #88141cff : 1685.79MH/s [A0+0:R0+0:F0]
  m  08:43:55|  Mining on PoWhash #88141cff : 1848.07MH/s [A0+0:R0+0:F0]
  m  08:43:56|  Mining on PoWhash #88141cff : 1876.44MH/s [A0+0:R0+0:F0]
  m  08:43:56|  Mining on PoWhash #88141cff : 1826.56MH/s [A0+0:R0+0:F0]
  m  08:43:57|  Mining on PoWhash #88141cff : 1845.66MH/s [A0+0:R0+0:F0]
  m  08:43:58|  Mining on PoWhash #88141cff : 1970.47MH/s [A0+0:R0+0:F0]
  m  08:43:59|  Mining on PoWhash #88141cff : 1997.93MH/s [A0+0:R0+0:F0]
  m  08:43:59|  Mining on PoWhash #88141cff : 1959.28MH/s [A0+0:R0+0:F0]
  m  08:44:00|  Mining on PoWhash #88141cff : 1945.89MH/s [A0+0:R0+0:F0]
  m  08:44:01|  Mining on PoWhash #88141cff : 1948.30MH/s [A0+0:R0+0:F0]
  m  08:44:01|  Mining on PoWhash #88141cff : 1917.52MH/s [A0+0:R0+0:F0]
  m  08:44:02|  Mining on PoWhash #88141cff : 1968.28MH/s [A0+0:R0+0:F0]
  m  08:44:03|  Mining on PoWhash #88141cff : 1974.48MH/s [A0+0:R0+0:F0]
  m  08:44:04|  Mining on PoWhash #88141cff : 1975.60MH/s [A0+0:R0+0:F0]
  m  08:44:04|  Mining on PoWhash #88141cff : 1897.88MH/s [A0+0:R0+0:F0]
  m  08:44:05|  Mining on PoWhash #88141cff : 1946.31MH/s [A0+0:R0+0:F0]
  m  08:44:06|  Mining on PoWhash #88141cff : 1985.48MH/s [A0+0:R0+0:F0]
  m  08:44:07|  Mining on PoWhash #88141cff : 1933.63MH/s [A0+0:R0+0:F0]
  m  08:44:07|  Mining on PoWhash #88141cff : 1940.09MH/s [A0+0:R0+0:F0]
  m  08:44:08|  Mining on PoWhash #88141cff : 1788.51MH/s [A0+0:R0+0:F0]
  m  08:44:09|  Mining on PoWhash #88141cff : 1937.95MH/s [A0+0:R0+0:F0]
  m  08:44:09|  Mining on PoWhash #88141cff : 1814.87MH/s [A0+0:R0+0:F0]
  m  08:44:10|  Got work package: #4a889c0b
  ℹ  08:44:10|openclminer0  set work; seed: #e0d55f3f, target:  #0000002af31d
  m  08:44:10|  Mining on PoWhash #4a889c0b : 1918.04MH/s [A0+0:R0+0:F0]
  m  08:44:11|  Mining on PoWhash #4a889c0b : 1981.05MH/s [A0+0:R0+0:F0]
  m  08:44:12|  Mining on PoWhash #4a889c0b : 1948.30MH/s [A0+0:R0+0:F0]
  m  08:44:12|  Mining on PoWhash #4a889c0b : 1981.78MH/s [A0+0:R0+0:F0]
  m  08:44:13|  Mining on PoWhash #4a889c0b : 1976.67MH/s [A0+0:R0+0:F0]
  m  08:44:14|  Mining on PoWhash #4a889c0b : 1949.08MH/s [A0+0:R0+0:F0]
  m  08:44:14|

**Comment by ArtSabintsev** [comment]
Oh man - this is beyond my understanding of how this is supposed to work. I'm assuming you know it's _not mining_ because no data is being update in the pool you're using?

**Comment by SnyderMark** [comment]
Wierd, I know. I'd love to be mining at 1949.08MH/s. Is there a way to have my eGPU do the mining?
Can I enable the -U command? How would I compile or recompile for the CUDA -U command to work? Would that make any difference?

**Comment by ArtSabintsev** [comment]
Honestly, I don't know. All I did was get the software working again, but that's the extent of my knowledge. Closing the issue, but feel free to follow up!
