### ISSUE TITLE
Could a precompiled ethminer (with CUDA enabled) be included in Releases?

### ISSUE THREAD

**Issue by jspinella** [ArtSabintsev/Ethminer-for-macOS#19]
I'm getting "The version ('90000') of the host compiler ('Apple clang') is not supported" when attempting to cmake ethminer with CUDA support enabled. I believe the solution is to install an older version of Xcode, however as most miners provide a precompiled version for users, I'm wondering if the same can be done for this fork for ethminer?

**Comment by ArtSabintsev** [comment]
This is being tracked here: #18 

I'm not doing any real active development of this work - just making sure it compiles, at least for now.

**Comment by jspinella** [comment]
Gotcha... Thank you!

**Comment by ArtSabintsev** [comment]
No problem - best of luck!
