### ISSUE TITLE
make -j8 failing

### ISSUE THREAD

**Issue by niksevalds** [ArtSabintsev/Ethminer-for-macOS#2]
Hi,

the "make -j8" command is failing for me on a Mac Pro 6,1 with AMD GPUs:

`ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libstratum/libethstratum.dylib] Error 1
make[1]: *** [libstratum/CMakeFiles/ethstratum.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 65%] Built target devcore
make: *** [all] Error 2`

**Comment by niksevalds** [comment]
Managed to resolve the issue with this: https://github.com/Genoil/cpp-ethereum/pull/200/files

**Comment by ArtSabintsev** [comment]
Using -DETHSTRATUM=1?

**Comment by niksevalds** [comment]
@ArtSabintsev no, I updated the `libstratum/CMakeLists.txt` file to include both devcore and ethcore target links.

The `libethcore/CMakeLists.txt` in your fork was exactly the same as in that pull request, but `libstratum/CMakeLists.txt` was not.

Then, after updating the .txt file the `make -j8` command worked.

**Comment by ArtSabintsev** [comment]
Got it - I just got it working with cudaminer as well.
Thanks!

I'll send a message to that guy as well and update the files on here.

**Comment by ArtSabintsev** [comment]
Fixed in v1.0.1, which was just released.

Thanks again for pointing this fix out.
