### ISSUE TITLE
issue with cmake -DBUNDLE=miner -DETHSTRATUM=1 ..

### ISSUE THREAD

**Issue by Harrythenoob** [ArtSabintsev/Ethminer-for-macOS#20]
Please provide the following information in your issue:
- Entire stacktrace, including your commands.
- Are you using OpenCL or CUDA?
  - There are issues with CUDA that have yet to be resolved. 

Hi, 
I'm new here so i'd like to say sorry in advance if i'm missing something. 
I keep getting stuck on the command "cmake -DBUNDLE=miner -DETHSTRATUM=1 ..
" 
terminal keeps returning with "command not found" 
and I have followed the previous steps exactly as stated. 
xcode version is 9.2 (9C40b) 
i'm trying to run this on a macbook pro with radeon pro 560

**Comment by ArtSabintsev** [comment]
Sorry for the late reply. It seems you don't have `cmake` installed.

Run `brew install cmake` and try again.
