### ISSUE TITLE
Question about compiling a static binary

### ISSUE THREAD

**Issue by timsutton** [ArtSabintsev/Ethminer-for-macOS#22]
Reading through the instructions on this repo gave me a working `ethminer` binary on the first try. Thanks for all your work on this!

I was wondering if there are any flags that can be provided to cmake / make to either 1) compile all dependent libraries into the final result so that it is static rather than dynamically-linked, or 2) (and I imagine this might be much less complex) link all the dylibs as relative, similar to how a macOS bundle can use rpath and include all of its dependencies.

Just thinking of ways to be able to build a full "release" of the miner so that it can be more easily distributed and self-contained.

Thanks again!

**Comment by ArtSabintsev** [comment]
Hey!

I'm not sure if that's possible, but then again, I'm not super qualified to answer this question. 

Part of the setup depends on:

- type of hardware on the machine, at compile-time and runtime
- access to xcodebuild

Just those two items makes me think the answer is `no`, but then again, feel free to explore!

Closing the ticket, but feel free to follow-up / reopen if you have more questions.

**Comment by ArtSabintsev** [comment]
Also, glad you got it working on your first try!
