### ISSUE TITLE
can not build on mac os 10.13 with CUDA_CUDART_LIBRARY version 9.1

### ISSUE THREAD

**Issue by KePeng1019** [ArtSabintsev/Ethminer-for-macOS#23]
Please provide the following information in your issue:
- Entire stacktrace, including your commands.
- Are you using OpenCL or CUDA?
  - There are issues with CUDA that have yet to be resolved.

**Comment by KePeng1019** [comment]
can not build because my cuda_cudart_library version 9.1.
I get this error:
`CMake Error at /usr/local/Cellar/cmake/3.11.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find CUDA (missing: CUDA_CUDART_LIBRARY) (found version "9.1")`

**Comment by ArtSabintsev** [comment]
Hi - I don't have a CUDA card, so I can't test, however, someone had a similar issue previously and augmented the README with a solution: https://github.com/ArtSabintsev/Ethminer-for-macOS#issues

Hope it helps!
