### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by jerrison** [ArtSabintsev/Ethminer-for-macOS#6]
SON-RPC problem. Probably couldn't connect. Retrying in 1...
  m  10:12:08|  Getting work package...
  ✘  10:12:18|  Failed to submit hashrate.
  ✘  10:12:18|  Dynamic exception type: jsonrpc::JsonRpcException
std::exception::what: Exception -32003 : Client connector error: libcurl error: 28 -> Operation timed out

**Comment by ArtSabintsev** [comment]
Please provide the full-stacktrace and commands you entered.

**Comment by jerrison** [comment]
./ethminer -G
Ethminer for macOS (Fixed by ArtSabintsev)

Forked from github.com/genoil/cpp-ethereum, which itself was forked from github.com/ethereum/cpp-ethereum.
CUDA kernel ported from Tim Hughes' OpenCL kernel
With contributions from nicehash, nerdralph, RoBiK and sp_

Please consider a donation to:
ArtSabintsev's ETH: 0x1e8cce03A2C01d18C5a68F410bfE34eea1aa16f2
Genoil's ETH: 0xeb9310b185455f863f526dab3d245809f6854b4d

[OPENCL]:Found suitable OpenCL device [Iris Pro] with 1610612736 bytes of GPU memory
  m  12:27:24|  Getting work package...
  ✘  12:27:24|  Failed to submit hashrate.
  ✘  12:27:24|  Dynamic exception type: jsonrpc::JsonRpcException
std::exception::what: Exception -32003 : Client connector error: libcurl error: 7 -> Could not connect to http://127.0.0.1:8545

JSON-RPC problem. Probably couldn't connect. Retrying in 1...

**Comment by fhorlaville** [comment]
You haven't provided a pool to mine with, therefore it's expecting a local server on port 8545 which it cannot find.

Here is the string I use (all on the same line):
`ethminer -G --opencl-device 1 --farm-recheck 200 -S eu1.ethermine.org:4444 -FS eu2.ethermine.org:14444 -O 0xeF6F1A52Cc04b5eDC97B6E57b4A7E5eb4e10166E.MacBookPro -v 1	
`

I first registered an account with ethermine.org - there are about a dozen of well-known active pools to choose from

you can get the list of options with ./ethminer --help

In this case:
```
-G : use the GPU
--opencl-device 1 : use my Radeon Pro card and not the integrated Intel card
--farm-recheck 200 : delay to check with the pool server
-S eu1.ethermine.org:4444 : the main pool server
-FS eu2.ethermine.org:14444 : the failover server in case the first one doesn't answer
-O 0xeF6F1A52Cc04b5eDC97B6E57b4A7E5eb4e10166E.MacBookPro : my username on the pool and the label I want to identify my machine
-v 1 : reduce verbosity (wastes processor and memory to display it all)

```

**Comment by jerrison** [comment]
Thanks @fhorlaville, now I get this issue...:

[OPENCL]:Found suitable OpenCL device [Iris Pro] with 1610612736 bytes of GPU memory
  ℹ  14:49:01|  Connecting to stratum server eu1.ethermine.org:4444
  ℹ  14:49:01|stratum  Connected to stratum server eu1.ethermine.org : 4444
  ℹ  14:49:01|stratum  Starting farm
  ℹ  14:49:02|stratum  Subscribed to stratum server
  ℹ  14:49:02|stratum  Authorized worker 0x9C70147404EBc889851E0266e5EcC9faE2426875.MacBookPro
  ℹ  14:49:02|stratum  Received new job #81613b5f
  ℹ  14:49:02|openclminer0  set work; seed: #129656ac, target:  #0000000112e0
  ℹ  14:49:02|openclminer0  Initialising miner...
[OPENCL]:Using platform: Apple
[OPENCL]:Using device: AMD Radeon R9 M370X Compute Engine(OpenCL 1.2 )
[OPENCL]:Printing program log
[OPENCL]:
[OPENCL]:Creating cache buffer
[OPENCL]:Creating DAG buffer
[OPENCL]:Allocating/mapping DAG buffer failed with: clCreateBuffer(-61). GPU can't allocate the DAG in a single chunk. Bailing.
[OPENCL]:clEnqueueWriteBuffer(-38)

**Comment by ArtSabintsev** [comment]
Ah, ok, I have the same issue. That means you can't mine because your hardware isn't powerful enough to mine. You prob have a card with 1GB or 2GB of RAM. You need at least a card with 4GB of memory these days. 

https://www.reddit.com/r/EtherMining/comments/6j10eb/increasing_dag_size_4gb_cards/
