### ISSUE TITLE
Error on Make

### ISSUE THREAD

**Issue by milezzz** [ArtSabintsev/Ethminer-for-macOS#9]
Using CUDA 8.0.61 on MacOS Sierra 10.12.5

When running `make -j8` I get:

[ 61%] Linking CXX shared library libdevcore.dylib
[ 61%] Built target devcore
make: *** [all] Error 2

Any idea?

**Comment by milezzz** [comment]
Gahhh finally got this to work, feel free to close this thread.

**Comment by ArtSabintsev** [comment]
What was wrong?
